language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
before_install:
  - sudo apt-get -y install wamerican
install:
  - pip install -r requirements.txt
script:
  - coverage run --branch --source=pypred -m py.test tests/
  - python bench.py
  - coverage report -m
